/**
 * English display layer for the Generator Builder's static field catalog
 * (`generator-field-catalog.ts`). The catalog data itself stays Turkish —
 * it is the source of truth for option `value` slugs, `jsonPath`s and stored
 * schemas, so nothing persisted may change. This file only maps each
 * Turkish display string (category / subgroup / field / option / package
 * labels and placeholders) to its English counterpart. Strings with no
 * entry (numbers, f-stops, format standards, brand/technology names such as
 * "TypeScript" or "GPT") are intentionally identical in both languages.
 */

import type { Language } from "@/lib/i18n/translations";
import type { CatalogField } from "@/lib/generator-field-catalog";

const RAW = `
Karakter Oluşturma => Character Creation
Kimlik => Identity
Ten / Cilt => Skin
Gözler => Eyes
Kaşlar => Eyebrows
Burun => Nose
Ağız / Dudak => Mouth / Lips
Saç => Hair
Sakal / Bıyık => Beard / Mustache
Vücut => Body
Kıyafet & Moda => Clothing & Fashion
Genel Stil => General Style
Üst Giyim => Tops
Alt Giyim => Bottoms
Ayakkabı => Footwear
Kumaş => Fabric
Renk / Desen => Color / Pattern
Aksesuar => Accessories
Takı => Jewelry
Baş => Head
Yüz => Face
Diğer => Other
Poz & Hareket => Pose & Motion
Temel Poz => Base Pose
Vücut Yönü => Body Direction
El Pozisyonu => Hand Position
Hareket Karakteri => Motion Style
Yüz İfadesi => Facial Expression
Duygu => Emotion
Göz İfadesi => Eye Expression
Ağız => Mouth
Yoğunluk => Intensity
Ortam & Mekân => Environment & Setting
Doğa => Nature
Şehir => City
İç Mekân => Interior
Fantastik => Fantasy
Sci-Fi => Sci-Fi
Hava & Atmosfer => Weather & Atmosphere
Hava => Weather
Atmosfer => Atmosphere
Partikül => Particles
Zaman => Time
Işıklandırma => Lighting
Işık Kaynağı => Light Source
Işık Yönü => Light Direction
Teknik => Technique
Karakter => Character
Renk => Color
Kamera & Lens => Camera & Lens
Çekim Türü => Shot Type
Kamera Açısı => Camera Angle
Lens => Lens
Diyafram => Aperture
Odak => Focus
Kamera Hareketi => Camera Movement
Çekim Ayarları => Shooting Settings
Görsel Stil => Visual Style
Gerçekçilik => Realism
3D => 3D
Anime => Anime
Sanat => Art
Sinematik => Cinematic
Tasarım Dili => Design Language
Renk & Palet => Color & Palette
Renkler => Colors
Renk Paleti => Color Palette
Ayarlar => Settings
Kompozisyon => Composition
Konu Konumu => Subject Placement
Kadraj => Framing
Derinlik => Depth
Perspektif => Perspective
Teknikler => Techniques
Görsel Efektler => Visual Effects
Işık Efektleri => Light Effects
Atmosferik => Atmospheric
Enerji => Energy
Kamera Efektleri => Camera Effects
Malzeme => Material
Yaratık => Creature
Dünya => World
Büyü => Magic
Sci-Fi & Cyberpunk => Sci-Fi & Cyberpunk
Teknoloji => Technology
Mekân => Setting
Stil => Style
Silah & Ekipman => Weapons & Gear
Yakın Dövüş => Melee
Uzak Dövüş => Ranged
Savunma => Defense
Detay => Detail
Ürün & Reklam => Product & Advertising
Ürün => Product
Ürün Çekimi => Product Shot
Arka Plan => Background
Reklam => Advertising
Pazarlama & Kampanya => Marketing & Campaign
Kampanya Türü => Campaign Type
Platform => Platform
Hedef Kitle => Target Audience
Çağrı (CTA) => Call to Action (CTA)
Ton => Tone
Format => Format
Video => Video
Video Türü => Video Type
Hareket => Motion
Geçiş => Transition
Ses & Müzik => Audio & Music
Tür / Janr => Genre
Ruh Hali => Mood
Enstrüman => Instrument
Vokal => Vocals
Tempo / Ritim => Tempo / Rhythm
Prodüksiyon => Production
Süre => Duration
Metin & İçerik => Text & Content
İçerik Türü => Content Type
Dil => Language
Uzunluk => Length
Yapı => Structure
Çıktı => Output
SEO => SEO
Kod & Yazılım => Code & Software
Framework => Framework
Veritabanı => Database
Mimari => Architecture
Test => Testing
AI / Prompt Ayarları => AI / Prompt Settings
Model => Model
Model Ayarları => Model Settings
Talimat => Instruction
UI / UX Tasarım => UI / UX Design
Yerleşim => Layout
Bileşen => Component
Tasarım Stili => Design Style
Erişilebilirlik => Accessibility
Fotoğraf => Photography
Fotoğraf Türü => Photo Type
Çekim Tekniği => Shooting Technique
Fotoğraf Karakteri => Photo Character
Negative & Quality => Negative & Quality
Kalite => Quality
Anatomik Hatalar => Anatomical Errors
Görsel Hatalar => Visual Errors
İstenmeyen Stil => Unwanted Style
Cinsiyet => Gender
Kadın => Female
Erkek => Male
Androjen => Androgynous
Belirsiz => Unspecified
Yaş Grubu => Age Group
Çocuk => Child
Genç => Young
Yetişkin => Adult
Orta Yaşlı => Middle-aged
Yaşlı => Elderly
Karakter Türü => Character Type
İnsan => Human
Android => Android
Robot => Robot
Cyborg => Cyborg
Elf => Elf
Ork => Orc
Vampir => Vampire
Zombi => Zombie
Uzaylı => Alien
Peri => Fairy
Melez => Hybrid
Mitolojik Varlık => Mythical Being
Rol => Role
Savaşçı => Warrior
Büyücü => Wizard
Suikastçı => Assassin
Şövalye => Knight
Kaşif => Explorer
Bilim İnsanı => Scientist
Öğrenci => Student
Doktor => Doctor
Asker => Soldier
Kraliçe => Queen
Kral => King
Hırsız => Thief
Tüccar => Merchant
Kişilik => Personality
Sakin => Calm
Gizemli => Mysterious
Neşeli => Cheerful
Sert => Tough
Cesur => Brave
Zarif => Elegant
Asi => Rebellious
Soğukkanlı => Cool-headed
Dost Canlısı => Friendly
Ciddi => Serious
Yüz Şekli => Face Shape
Oval => Oval
Yuvarlak => Round
Kare => Square
Kalp => Heart
Elmas => Diamond
Uzun => Long
Ten Rengi => Skin Tone
Çok Açık => Very Fair
Açık => Light
Buğday => Wheat
Esmer => Tan
Koyu => Dark
Çok Koyu => Very Dark
Cilt Dokusu => Skin Texture
Pürüzsüz => Smooth
Doğal => Natural
Gözenekli => Porous
Hasarlı => Damaged
Çil => Freckles
Yok => None
Hafif => Light
Orta => Medium
Yoğun => Heavy
Dövme => Tattoo
Küçük => Small
Büyük => Large
Tüm Vücut => Full Body
Yara İzi => Scar
İnce => Thin
Belirgin => Prominent
Göz Rengi => Eye Color
Mavi => Blue
Yeşil => Green
Kahverengi => Brown
Gri => Gray
Ela => Hazel
Amber => Amber
Mor => Purple
Kırmızı => Red
Siyah => Black
Göz Şekli => Eye Shape
Badem => Almond
Çekik => Upturned
Derin Set => Deep-set
Göz Boyutu => Eye Size
Göz Efekti => Eye Effect
Glow => Glow
Büyülü => Magical
Neon => Neon
Kaş Şekli => Eyebrow Shape
Düz => Straight
Kavisli => Curved
Keskin => Sharp
Kaş Rengi => Eyebrow Color
Sarı => Blonde
Kızıl => Red-haired
Beyaz => White
Burun Şekli => Nose Shape
Geniş => Wide
Kalkık => Upturned Nose
Roma => Roman
Dudak Şekli => Lip Shape
Dolgun => Full
Çok Dolgun => Very Full
Dudak Rengi => Lip Color
Pembe => Pink
Bordo => Burgundy
Diş => Teeth
Görünmüyor => Not Visible
Vampir Dişleri => Vampire Fangs
Saç Uzunluğu => Hair Length
Kel => Bald
Çok Kısa => Very Short
Kısa => Short
Çok Uzun => Very Long
Saç Şekli => Hair Style
Dalgalı => Wavy
Kıvırcık => Curly
Afro => Afro
Örgülü => Braided
At Kuyruğu => Ponytail
Topuz => Bun
Bob => Bob
Pixie => Pixie
Dağınık => Messy
Saç Rengi => Hair Color
Platin => Platinum
Gümüş => Silver
Saç Dokusu => Hair Texture
Normal => Normal
Kalın => Thick
İpeksi => Silky
Kabarık => Fluffy
Perçem => Bangs
Yan => Side
Perde => Curtain
Sakal => Beard
Kirli Sakal => Stubble
Tam Sakal => Full Beard
Bıyık => Mustache
Klasik => Classic
Dönük => Curled
Vücut Tipi => Body Type
Zayıf => Slim
Atletik => Athletic
Fit => Fit
Kaslı => Muscular
Güçlü => Strong
Kilolu => Heavyset
Boy => Height
Kas Seviyesi => Muscle Level
Düşük => Low
Yüksek => High
Çok Yüksek => Very High
Vücut Oranı => Body Proportions
Gerçekçi => Realistic
Stilize => Stylized
Karikatürize => Caricatured
Duruş => Posture
Dik => Upright
Rahat => Relaxed
Kambur => Hunched
Gururlu => Proud
Yorgun => Tired
Askeri => Military
Günlük => Casual
Resmi => Formal
Sokak Modası => Streetwear
Lüks => Luxury
Vintage => Vintage
Minimal => Minimal
Sportif => Sporty
Gotik => Gothic
Punk => Punk
Cyberpunk => Cyberpunk
Geleneksel => Traditional
Moda Dönemi => Fashion Era
Modern => Modern
1920'ler => 1920s
1950'ler => 1950s
1970'ler => 1970s
1980'ler => 1980s
1990'lar => 1990s
Fütüristik => Futuristic
Üst Türü => Top Type
Tişört => T-Shirt
Gömlek => Shirt
Bluz => Blouse
Kazak => Sweater
Sweatshirt => Sweatshirt
Hoodie => Hoodie
Ceket => Jacket
Deri Ceket => Leather Jacket
Mont => Coat
Kaban => Overcoat
Zırh => Armor
Kol Tipi => Sleeve Type
Kolsuz => Sleeveless
Bol => Loose
Dar => Tight
Yaka => Collar
V Yaka => V-Neck
Gömlek Yaka => Shirt Collar
Balıkçı => Turtleneck
Açık Yaka => Open Collar
Alt Türü => Bottom Type
Jean => Jeans
Pantolon => Trousers
Şort => Shorts
Etek => Skirt
Tayt => Leggings
Kargo Pantolon => Cargo Pants
Eşofman => Sweatpants
Kesim => Fit
Dar Kesim => Slim Fit
İnce Kesim => Skinny Fit
Normal Kesim => Regular Fit
Rahat Kesim => Comfort Fit
Bol Kesim => Loose Fit
Bol Paça => Wide Leg
Ayakkabı Türü => Shoe Type
Sneaker => Sneakers
Bot => Boots
Çizme => Tall Boots
Topuklu => Heels
Sandalet => Sandals
Loafer => Loafers
Spor Ayakkabı => Athletic Shoes
Ayakkabı Rengi => Shoe Color
Altın => Gold
Pamuk => Cotton
Keten => Linen
İpek => Silk
Kadife => Velvet
Deri => Leather
Denim => Denim
Yün => Wool
Saten => Satin
Naylon => Nylon
Doku => Texture
Mat => Matte
Parlak => Glossy
Yumuşak => Soft
Metalik => Metallic
Ana Renk => Primary Color
Desen => Pattern
Çizgili => Striped
Kareli => Checkered
Çiçekli => Floral
Geometrik => Geometric
Kamuflaj => Camouflage
Renk Geçişi => Color Gradient
Desen Yoğunluğu => Pattern Density
Kolye => Necklace
İnce Zincir => Thin Chain
Kalın Zincir => Thick Chain
Taşlı Kolye => Gemstone Necklace
Madalyon => Pendant
Küpe => Earrings
Halka => Hoop
Taşlı => Gemstone
Sade => Plain
Piercing => Piercing
Yüzük => Ring
Sade Yüzük => Plain Ring
Taşlı Yüzük => Gemstone Ring
Büyülü Yüzük => Magic Ring
Baş Aksesuarı => Head Accessory
Şapka => Hat
Bere => Beanie
Taç => Crown
Bandana => Bandana
Saç Aksesuarı => Hair Accessory
Gözlük => Glasses
Şeffaf Gözlük => Clear Glasses
Güneş Gözlüğü => Sunglasses
Maske => Mask
Yüz Piercingi => Face Piercing
Çanta => Bag
Sırt Çantası => Backpack
Bel Çantası => Waist Bag
Diğer Aksesuarlar => Other Accessories
Eldiven => Gloves
Saat => Watch
Bileklik => Bracelet
Kulaklık => Headphones
Telefon => Phone
Anahtarlık => Keychain
Broş => Brooch
Ayakta => Standing
Oturuyor => Sitting
Yatıyor => Lying Down
Diz Çöküyor => Kneeling
Yürüyor => Walking
Koşuyor => Running
Zıplıyor => Jumping
Dans Ediyor => Dancing
Önden => Front
Arkadan => Back
Yandan => Side View
3/4 => 3/4
Kameraya Dönük => Facing Camera
Kameradan Uzak => Facing Away
Eller Aşağıda => Hands Down
Ceplerde => In Pockets
Göğüste => On Chest
Yüzde => On Face
Saçta => In Hair
Bir Şey Tutuyor => Holding Something
Silah Tutuyor => Holding a Weapon
Telefon Tutuyor => Holding a Phone
Baş Pozisyonu => Head Position
Sola Eğik => Tilted Left
Sağa Eğik => Tilted Right
Yukarı Bakıyor => Looking Up
Aşağı Bakıyor => Looking Down
Kameraya Bakıyor => Looking at Camera
Kameradan Uzak Bakıyor => Looking Away
Statik => Static
Dinamik => Dynamic
Aksiyon => Action
Hızlı => Fast
Yavaş => Slow
Mutlu => Happy
Üzgün => Sad
Öfkeli => Angry
Korkmuş => Scared
Şaşkın => Surprised
Romantik => Romantic
Kararlı => Determined
Yumuşak Bakış => Soft Gaze
Yoğun Bakış => Intense Gaze
Keskin Bakış => Sharp Gaze
Uykulu => Sleepy
Kameraya Bakış => Gaze at Camera
Uzaklara Bakış => Distant Gaze
Kapalı => Closed
Hafif Gülümseme => Slight Smile
Gülümseme => Smile
Kahkaha => Laughing
Hafif Açık => Slightly Open
Doğa Mekânı => Nature Setting
Orman => Forest
Dağ => Mountain
Çöl => Desert
Plaj => Beach
Okyanus => Ocean
Göl => Lake
Şelale => Waterfall
Mağara => Cave
Çayır => Meadow
Kar Manzarası => Snowy Landscape
Şehir Mekânı => City Setting
Modern Şehir => Modern City
Eski Şehir => Old Town
Tokyo Tarzı => Tokyo Style
New York Tarzı => New York Style
Avrupa Şehri => European City
Gece Şehri => Night City
Neon Şehir => Neon City
Endüstriyel Bölge => Industrial District
Ev => Home
Ofis => Office
Kafe => Cafe
Restoran => Restaurant
Otel => Hotel
Kütüphane => Library
Stüdyo => Studio
Hastane => Hospital
Mağaza => Store
Spor Salonu => Gym
Fantastik Mekân => Fantasy Setting
Büyülü Orman => Enchanted Forest
Kale => Castle
Antik Tapınak => Ancient Temple
Ejderha Mağarası => Dragon Cave
Büyü Akademisi => Magic Academy
Mitolojik Şehir => Mythical City
Sci-Fi Mekân => Sci-Fi Setting
Uzay İstasyonu => Space Station
Laboratuvar => Laboratory
Cyberpunk Sokak => Cyberpunk Street
Gelecek Şehri => Future City
Robot Fabrikası => Robot Factory
Uzay Gemisi => Spaceship
Hava Durumu => Weather Condition
Güneşli => Sunny
Bulutlu => Cloudy
Yağmurlu => Rainy
Karlı => Snowy
Sisli => Foggy
Fırtınalı => Stormy
Açık Gökyüzü => Clear Sky
Karanlık => Dark
Epik => Epic
Gerilimli => Tense
Huzurlu => Peaceful
Rüya Gibi => Dreamlike
Toz => Dust
Kar => Snow
Yağmur => Rain
Kül => Ash
Yaprak => Leaves
Kıvılcım => Sparks
Sis => Fog
Duman => Smoke
Şafak => Dawn
Sabah => Morning
Öğlen => Noon
Gün Batımı => Sunset
Alacakaranlık => Twilight
Gece => Night
Gece Yarısı => Midnight
Güneş => Sun
Ay => Moon
Mum => Candle
Sokak Lambası => Street Lamp
Stüdyo Işığı => Studio Light
Ateş => Fire
Büyülü Işık => Magical Light
LED => LED
Üstten => From Above
Alttan => From Below
Kenar Işığı => Rim Light
Yumuşak Işık => Soft Light
Sert Işık => Hard Light
Yayılmış Işık => Diffused Light
Volümetrik => Volumetric
Global Aydınlatma => Global Illumination
Sinematik Aydınlatma => Cinematic Lighting
Stüdyo Aydınlatması => Studio Lighting
Işık Karakteri => Light Character
High Key => High Key
Low Key => Low Key
Dramatik => Dramatic
Karanlık Ruh Halli => Dark Mood
Işık Rengi => Light Color
Sıcak => Warm
Soğuk => Cool
Nötr => Neutral
Turuncu/Mavi => Orange/Blue
Mor/Mavi => Purple/Blue
Portre => Portrait
Tam Boy => Full Length
Yarım Boy => Half Length
Yakın Plan => Close-up
Ekstrem Yakın Plan => Extreme Close-up
Manzara => Landscape
Göz Hizası => Eye Level
Alttan Açı => Low Angle
Üstten Açı => High Angle
Kuşbakışı => Bird's-eye View
Solucan Bakışı => Worm's-eye View
Eğik Açı => Dutch Angle
Omuz Üzerinden => Over the Shoulder
Lens (mm) => Lens (mm)
Telefoto => Telephoto
Makro => Macro
Balık Gözü => Fisheye
Konu Odakta => Subject in Focus
Arka Plan Odakta => Background in Focus
Her Şey Odakta => Everything in Focus
Sığ Alan Derinliği => Shallow Depth of Field
Derin Alan Derinliği => Deep Depth of Field
Sabit => Static
Enstantane Hızı => Shutter Speed
1sn (Uzun Pozlama) => 1s (Long Exposure)
Beyaz Ayarı => White Balance
Otomatik => Auto
Gün Işığı => Daylight
Tungsten => Tungsten
Floresan => Fluorescent
Gölge => Shade
Fotogerçekçi => Photorealistic
Hipergerçekçi => Hyperrealistic
Stilize Gerçekçilik => Stylized Realism
Yarı Gerçekçi => Semi-realistic
3D Stili => 3D Style
3D Karakter => 3D Character
3D Animasyon => 3D Animation
Stilize 3D => Stylized 3D
Gerçekçi 3D => Realistic 3D
Oyun Karakteri => Game Character
CGI => CGI
Anime Stili => Anime Style
Manga => Manga
Japon Animasyonu => Japanese Animation
Cel Shading => Cel Shading
Yarı Gerçekçi Anime => Semi-realistic Anime
Sanat Stili => Art Style
Yağlı Boya => Oil Painting
Suluboya => Watercolor
Akrilik => Acrylic
Kalem Çizimi => Pencil Drawing
Mürekkep => Ink
Konsept Sanat => Concept Art
Dijital Boyama => Digital Painting
Matte Painting => Matte Painting
Sinematik Stil => Cinematic Style
Film Karesi => Film Still
Belgesel => Documentary
Karanlık Sinematik => Dark Cinematic
Editoryal => Editorial
Moda => Fashion
Retro => Retro
Deneysel => Experimental
İkincil Renk => Secondary Color
Vurgu Rengi => Accent Color
Arka Plan Rengi => Background Color
Tek Renkli => Monochrome
Tamamlayıcı Renkler => Complementary Colors
Komşu Renkler => Analogous Colors
Üçlü Renk Uyumu => Triadic Colors
Pastel => Pastel
Toprak Tonları => Earth Tones
Siyah & Beyaz => Black & White
Doygunluk => Saturation
Kontrast => Contrast
Parlaklık => Brightness
Sıcaklık => Temperature
Merkez => Center
Sol => Left
Sağ => Right
Üst => Top
Alt => Bottom
Köşe => Corner
Tam Kare => Full Frame
Orta Plan => Medium Shot
Yakın Çekim => Close Shot
Geniş Çekim => Wide Shot
Ekstrem Geniş Çekim => Extreme Wide Shot
Ön Plan => Foreground
Katmanlı => Layered
Derin => Deep
Çarpıtılmış => Distorted
Zorlanmış Perspektif => Forced Perspective
Kompozisyon Tekniği => Composition Technique
Üçte Bir Kuralı => Rule of Thirds
Merkezi Kompozisyon => Centered Composition
Simetri => Symmetry
Yönlendirici Çizgiler => Leading Lines
Çerçeveleme => Framing
Negatif Alan => Negative Space
Diyagonal Kompozisyon => Diagonal Composition
Katmanlama => Layering
Altın Oran => Golden Ratio
Parıltı => Sparkle
Bloom => Bloom
Lens Flare => Lens Flare
Işık Huzmeleri => Light Beams
Tanrı Işınları => God Rays
Volümetrik Işık => Volumetric Light
Atmosferik Efektler => Atmospheric Effects
Pus => Haze
İnce Sis => Light Mist
Doğa Efektleri => Nature Effects
Yapraklar => Leaves
Taç Yaprakları => Petals
Kum => Sand
Enerji Efektleri => Energy Effects
Büyü Parçacıkları => Magic Particles
Yıldırım => Lightning
Buz => Ice
Elektrik => Electricity
Aura => Aura
Hareket Bulanıklığı => Motion Blur
Alan Derinliği => Depth of Field
Kromatik Sapma => Chromatic Aberration
Film Grenı => Film Grain
Vinyet => Vignette
Bokeh => Bokeh
Malzeme Efektleri => Material Effects
Yansıma => Reflection
Kırılma => Refraction
Cam => Glass
Islak Yüzey => Wet Surface
Metalik Parlaklık => Metallic Sheen
Fantastik Karakter => Fantasy Character
Kara Elf => Dark Elf
Cüce => Dwarf
İblis => Demon
Melek => Angel
Ejderha Binicisi => Dragon Rider
Cadı => Witch
Ejderha => Dragon
Anka Kuşu => Phoenix
Grifon => Griffin
Kurt => Wolf
Dev => Giant
Element Yaratığı => Elemental Creature
Canavar => Monster
Mitolojik Yaratık => Mythical Creature
Fantastik Krallık => Fantasy Kingdom
Antik Kalıntılar => Ancient Ruins
Yüzen Adalar => Floating Islands
Yeraltı Dünyası => Underworld
Göksel Diyar => Celestial Realm
Büyü Türü => Magic Type
Ateş Büyüsü => Fire Magic
Buz Büyüsü => Ice Magic
Yıldırım Büyüsü => Lightning Magic
Karanlık Büyü => Dark Magic
Işık Büyüsü => Light Magic
Doğa Büyüsü => Nature Magic
Gizemli Büyü => Arcane Magic
İyileştirme Büyüsü => Healing Magic
Sci-Fi Karakter => Sci-Fi Character
Uzay Askeri => Space Marine
Hacker => Hacker
Pilot => Pilot
Mühendis => Engineer
Hologram => Hologram
Nöral Arayüz => Neural Interface
Sibernetik Kol => Cybernetic Arm
Mekanik Göz => Mechanical Eye
Enerji Çekirdeği => Energy Core
Yapay Zekâ Asistanı => AI Assistant
Nanoteknoloji => Nanotechnology
Cyberpunk Sokağı => Cyberpunk Street
Mega Şehir => Megacity
Fabrika => Factory
Uzay Aracı => Spacecraft
Neon Sokak => Neon Street
Synthwave => Synthwave
Endüstriyel Bilim Kurgu => Industrial Sci-Fi
Retro-Fütürizm => Retro-Futurism
Uzay Operası => Space Opera
Yakın Dövüş Silahı => Melee Weapon
Kılıç => Sword
Katana => Katana
Balta => Axe
Mızrak => Spear
Hançer => Dagger
Çekiç => Hammer
Asa => Staff
Uzak Dövüş Silahı => Ranged Weapon
Yay => Bow
Arbalet => Crossbow
Enerji Silahı => Energy Weapon
Bilim Kurgu Silahı => Sci-Fi Weapon
Fantastik Menzilli Silah => Fantasy Ranged Weapon
Savunma Ekipmanı => Defensive Gear
Kalkan => Shield
Kask => Helmet
Omuzluk => Pauldron
Ekipman Detayı => Gear Detail
Metal => Metal
Ahşap => Wood
Kristal => Crystal
Rün => Rune
Gravür => Engraving
Ürün Kategorisi => Product Category
Tablet => Tablet
Laptop => Laptop
Kozmetik => Cosmetics
Mobilya => Furniture
Elektronik => Electronics
Otomotiv => Automotive
Stüdyo Ürünü => Studio Product
Ana Çekim => Hero Shot
Yaşam Tarzı => Lifestyle
Üstten Düzen => Flat Lay
360 Derece Ürün => 360° Product
Renk Geçişli => Gradient
Reklam Stili => Ad Style
Premium => Premium
Ticari => Commercial
Sosyal Medya Reklamı => Social Media Ad
Referans Görsel URL => Reference Image URL
Google Ads => Google Ads
Email Kampanyası => Email Campaign
Influencer İşbirliği => Influencer Collaboration
Lansman Kampanyası => Launch Campaign
İndirim Kampanyası => Discount Campaign
Marka Bilinirliği => Brand Awareness
Yeniden Hedefleme => Retargeting
Kampanya Hedefi => Campaign Goal
Satış => Sales
Trafik => Traffic
Takipçi Kazanımı => Follower Growth
Potansiyel Müşteri Toplama => Lead Generation
Uygulama İndirme => App Installs
Instagram => Instagram
Facebook => Facebook
TikTok => TikTok
YouTube => YouTube
LinkedIn => LinkedIn
Twitter/X => Twitter/X
Google => Google
E-posta => Email
Web Sitesi => Website
Reklam Formatı => Ad Format
Statik Görsel => Static Image
Carousel => Carousel
Kısa Video => Short Video
Story => Story
Banner => Banner
Newsletter => Newsletter
Genç Yetişkin => Young Adult
Aile => Family
Profesyonel => Professional
Girişimci => Entrepreneur
Genel => General
Yaş Aralığı => Age Range
Şimdi Al => Buy Now
Kaydol => Sign Up
Daha Fazla Bilgi => Learn More
Ücretsiz Dene => Try for Free
İletişime Geç => Contact Us
İndir => Download
Sepete Ekle => Add to Cart
Aciliyet Vurgusu => Urgency Emphasis
Sınırlı Süre => Limited Time
Sınırlı Stok => Limited Stock
Son Gün => Last Day
Yalnızca Bugün => Today Only
Enerjik => Energetic
Güven Verici => Reassuring
Eğlenceli => Fun
Samimi => Warm
İndirim Oranı (%) => Discount Rate (%)
Başlık Fikri => Headline Idea
Örn. Yaza Hazır Ol, %30 İndirim => e.g. Get Ready for Summer, 30% Off
Marka Sesi => Brand Voice
Ciddi/Kurumsal => Serious/Corporate
Arkadaşça => Friendly
Esprili => Witty
İlham Verici => Inspiring
Cesur/Rahatsız Edici => Bold/Provocative
Kısa Film => Short Film
Müzik Videosu => Music Video
Sosyal Medya => Social Media
Ürün Videosu => Product Video
Animasyon => Animation
Süre (sn) => Duration (sec)
En-Boy Oranı => Aspect Ratio
Takip => Tracking
Yörünge => Orbit
El Kamerası => Handheld
Vinç => Crane
Karakter Hareketi => Character Movement
Yürüme => Walking
Koşma => Running
Dönme => Turning
Bakma => Looking
El Kol Hareketi => Gesturing
Dövüşme => Fighting
Dans Etme => Dancing
Oturma => Sitting
Ayakta Durma => Standing
Kesme => Cut
Karartma => Fade to Black
Çözülme => Dissolve
Yakınlaştırma => Zoom
Eşleşen Kesme => Match Cut
Hızlı Pan => Whip Pan
Pop => Pop
Rock => Rock
Hip-Hop => Hip-Hop
Jazz => Jazz
Lo-fi => Lo-fi
Ambient => Ambient
Folk => Folk
R&B => R&B
Alt Tür => Subgenre
Örn. Synthwave, Deep House => e.g. Synthwave, Deep House
Hüzünlü => Melancholic
Gergin => Tense
Rahatlatıcı => Relaxing
Enerji Seviyesi => Energy Level
Ana Enstrüman => Lead Instrument
Piyano => Piano
Gitar => Guitar
Keman => Violin
Davul => Drums
Bas => Bass
Synth => Synth
Flüt => Flute
Saksafon => Saxophone
Orkestra => Orchestra
Perküsyon => Percussion
Enstrümantal (Vokalsiz) => Instrumental (No Vocals)
Erkek Vokal => Male Vocals
Kadın Vokal => Female Vocals
Koro => Choir
Rap => Rap
Fısıltı => Whisper
Opera Tarzı => Operatic
Duet => Duet
Vokal Dili => Vocal Language
Türkçe => Turkish
İngilizce => English
Çok Dilli => Multilingual
Tempo => Tempo
Çok Yavaş => Very Slow
Çok Hızlı => Very Fast
BPM => BPM
Stüdyo Kalitesi => Studio Quality
Lo-fi / Ham => Lo-fi / Raw
Canlı Kayıt => Live Recording
Elektronik / Sentetik => Electronic / Synthetic
Akustik => Acoustic
Ses Efektleri => Sound Effects
Reverb => Reverb
Echo => Echo
Distortion => Distortion
Autotune => Autotune
Vinyl Crackle => Vinyl Crackle
Sidechain => Sidechain
15sn => 15s
30sn => 30s
1dk => 1 min
2dk => 2 min
3dk => 3 min
Tam Şarkı => Full Song
Blog => Blog
Makale => Article
Ürün Açıklaması => Product Description
Haber => News
Senaryo => Script
Hikâye => Story
Şiir => Poem
Akademik => Academic
Pazarlama => Marketing
Almanca => German
Fransızca => French
İspanyolca => Spanish
İtalyanca => Italian
Arapça => Arabic
İkna Edici => Persuasive
Kelime Sayısı => Word Count
Başlık => Title
Giriş => Introduction
Bölümler => Sections
Maddeler => Bullet Points
Sonuç => Conclusion
CTA => CTA
Çıktı Formatı => Output Format
Düz Metin => Plain Text
Markdown => Markdown
Tablo => Table
Madde İşaretleri => Bullet List
Anahtar Kelime => Keyword
Örn. organik kahve çekirdeği => e.g. organic coffee beans
Meta Açıklama => Meta Description
Programlama Dili => Programming Language
Monolitik => Monolithic
Mikroservisler => Microservices
Sunucusuz => Serverless
Olay Güdümlü => Event-driven
Kod => Code
Açıklama => Description
Testler => Tests
Dokümantasyon => Documentation
Fark (Diff) => Diff
Dosya Yapısı => File Structure
Test Türü => Test Type
Birim Testi => Unit Test
Entegrasyon Testi => Integration Test
Uçtan Uca Test => End-to-End Test
Anlık Görüntü Testi => Snapshot Test
Test Kapsama Hedefi (%) => Test Coverage Target (%)
Görsel Modeli => Image Model
Video Modeli => Video Model
Özel Model => Custom Model
Maksimum Token Sayısı => Max Tokens
Örn. Kıdemli backend mühendisi => e.g. Senior backend engineer
Amaç => Objective
Kısıtlar => Constraints
Mobil Web => Mobile Web
Masaüstü => Desktop
Kontrol Paneli => Dashboard
Açılış Sayfası => Landing Page
Akış => Feed
Profil => Profile
Yönetim Paneli => Admin Panel
E-Ticaret => E-Commerce
Navigasyon Çubuğu => Navigation Bar
Kenar Menü => Sidebar
Kart => Card
Modal => Modal
Form => Form
Sekmeler => Tabs
Akordeon => Accordion
Açılır Menü => Dropdown
Bildirim => Notification
Arama => Search
Sayfalama => Pagination
Glassmorphism => Glassmorphism
Neumorphism => Neumorphism
Brütalist => Brutalist
Soft UI => Soft UI
Material => Material
Apple Tarzı => Apple Style
Erişilebilirlik Seviyesi => Accessibility Level
Renk Kontrastı => Color Contrast
Standart => Standard
Yüksek Kontrast => High Contrast
Renk Körü Dostu => Colorblind-friendly
Sokak => Street
Yemek => Food
Düğün => Wedding
Uzun Pozlama => Long Exposure
Hareketi Dondurma => Freeze Motion
Ham => Raw
Film => Film
Polaroid => Polaroid
Üst Düzey Moda => High Fashion
Yüksek Kalite => High Quality
Ultra Detaylı => Ultra Detailed
Temiz => Clean
Yüksek Çözünürlük => High Resolution
Anatomik Hatalar (kaçınılacak) => Anatomical Errors (to avoid)
Fazla Parmak => Extra Fingers
Fazla Uzuv => Extra Limbs
Deforme Eller => Deformed Hands
Bozuk Anatomi => Broken Anatomy
Çarpık Yüz => Distorted Face
Asimetrik Gözler => Asymmetrical Eyes
Görsel Hatalar (kaçınılacak) => Visual Errors (to avoid)
Bulanıklık => Blur
Gürültü => Noise
Pikselli => Pixelated
Düşük Çözünürlük => Low Resolution
Aşırı Pozlanmış => Overexposed
Yetersiz Pozlanmış => Underexposed
Görüntü Artefaktları => Image Artifacts
Sıkıştırma Bozulması => Compression Artifacts
İstenmeyen Stil (kaçınılacak) => Unwanted Style (to avoid)
Düşük Kalite => Low Quality
Amatör => Amateur
Aşırı Doygun Renkler => Oversaturated Colors
Düz Aydınlatma => Flat Lighting
Kötü Kompozisyon => Poor Composition
Bozuk Perspektif => Broken Perspective
Temel Karakter => Basic Character
Yüz Detayları => Face Details
Göz Detayları => Eye Details
Saç Detayları => Hair Details
Vücut Anatomisi => Body Anatomy
Kıyafet => Clothing
Poz => Pose
Ortam => Environment
Kamera => Camera
Efektler => Effects
Fantastik Kurulum => Fantasy Setup
Sci-Fi Kurulum => Sci-Fi Setup
Video Temelleri => Video Basics
İçerik Brifi => Content Brief
Kod Projesi => Code Project
AI Prompt Ayarları => AI Prompt Settings
Arayüz Ekranı => UI Screen
Fotoğraf Çekimi => Photo Shoot
Müzik Parçası => Music Track
Reklam Kampanyası => Ad Campaign
Aksesuarlar => Accessories
`;

const EN = new Map<string, string>(
  RAW.split("\n")
    .map((line) => line.split(" => "))
    .filter((parts): parts is [string, string] => parts.length === 2)
    .map(([tr, en]) => [tr.trim(), en.trim()]),
);

/** Localizes one catalog display string; unknown strings pass through unchanged. */
export function catalogText(tr: string, language: Language): string {
  return language === "en" ? (EN.get(tr) ?? tr) : tr;
}

/** True when `text` (Turkish) or its English counterpart contains `needle` after `normalize`. */
export function catalogTextMatches(tr: string, needle: string, normalize: (value: string) => string): boolean {
  return normalize(tr).includes(needle) || normalize(EN.get(tr) ?? tr).includes(needle);
}

/**
 * A copy of `field` with label/placeholder/option labels in `language` —
 * used when inserting into a generator so the creator's schema is written in
 * the language they are working in. Option `value`s, `jsonPath`, images and
 * colors are never touched.
 */
export function localizeCatalogField(field: CatalogField, language: Language): CatalogField {
  if (language !== "en") return field;
  return {
    ...field,
    label: catalogText(field.label, language),
    placeholder: field.placeholder ? catalogText(field.placeholder, language) : field.placeholder,
    options: field.options.map((option) => ({ ...option, label: catalogText(option.label, language) })),
  };
}
