/**
 * Taxonomy SEED — the bundled copy of the content taxonomy (content type ->
 * category -> subcategory) that is ALSO inserted into the database
 * (`taxonomy_categories` / `taxonomy_subcategories`, migration
 * 20260919570000). The database is the source of truth at runtime
 * (`TaxonomyHydrator` replaces this data with the live rows); this file is the
 * offline fallback / first paint and the single place the SQL seed is
 * generated from. Pure data, no imports, so a script can load it directly.
 *
 * A category entry is `[[en, tr], [subcategory pairs], iconName, [descEn, descTr]]`.
 * The stored slug of every node is derived from its ENGLISH name and never
 * changes (it is what prompts/requests/generators store); only the visible
 * labels may be edited.
 */
export type ContentTypeId = "image" | "text" | "audio" | "video";
export const CONTENT_TYPE_IDS: readonly ContentTypeId[] = ["image", "text", "audio", "video"];

/** [English, Türkçe] */
export type Pair = readonly [string, string];
export type RawCategory = readonly [Pair, readonly Pair[], string, Pair];

const P = (en: string, tr: string): Pair => [en, tr];

export const TAXONOMY_SEED: Record<ContentTypeId, readonly RawCategory[]> = {
  image: [
    [P("Human & Character", "İnsan & Karakter"), [P("Portrait", "Portre"), P("Character", "Karakter"), P("Character Design", "Karakter Tasarımı"), P("Human", "İnsan"), P("Child", "Çocuk"), P("Elderly", "Yaşlı"), P("Group", "Grup"), P("Couple", "Çift"), P("Fashion", "Moda"), P("Beauty", "Güzellik"), P("Makeup", "Makyaj"), P("Hair", "Saç"), P("Body & Pose", "Vücut / Poz")], "users", P("People, characters and portrait-led visuals.", "Portreler, karakterler ve insan odaklı görseller.")],
    [P("Photography", "Fotoğrafçılık"), [P("Portrait Photography", "Portre Fotoğrafı"), P("Street Photography", "Sokak Fotoğrafı"), P("Landscape", "Manzara"), P("Nature", "Doğa"), P("Night Photography", "Gece Fotoğrafı"), P("Studio", "Stüdyo"), P("Wedding", "Düğün"), P("Travel", "Seyahat"), P("Architectural Photography", "Mimari Fotoğraf"), P("Product Photography", "Ürün Fotoğrafı"), P("Food Photography", "Yemek Fotoğrafı"), P("Fashion Photography", "Moda Fotoğrafı"), P("Macro", "Makro"), P("Wildlife", "Vahşi Yaşam"), P("Minimal", "Minimal"), P("Cinematic Photography", "Sinematik"), P("Black & White", "Siyah Beyaz")], "camera", P("Photography genres and shooting styles.", "Fotoğraf türleri ve çekim tarzları.")],
    [P("Art & Illustration", "Sanat & İllüstrasyon"), [P("Digital Art", "Dijital Sanat"), P("Concept Art", "Konsept Sanat"), P("Illustration", "İllüstrasyon"), P("Cartoon", "Karikatür"), P("Drawing", "Çizim"), P("Oil Painting", "Yağlı Boya"), P("Watercolor", "Suluboya"), P("Sketch", "Eskiz"), P("Pixel Art", "Pixel Art"), P("Poster", "Poster"), P("Collage", "Kolaj"), P("Character Illustration", "Karakter İllüstrasyonu"), P("Painting", "Boyama"), P("Anime Art", "Anime"), P("Manga Art", "Manga"), P("3D Art", "3D"), P("Fantasy Art", "Fantastik"), P("Sci-Fi Art", "Bilim Kurgu"), P("Children's Illustration", "Çocuk İllüstrasyonu")], "palette", P("Drawing, painting and illustration work.", "Çizim, boyama ve illüstrasyon çalışmaları.")],
    [P("Style", "Stil"), [P("Realistic", "Gerçekçi"), P("Cinematic", "Sinematik"), P("Anime", "Anime"), P("Manga", "Manga"), P("3D", "3D"), P("Pixar-style", "Pixar Benzeri"), P("Cyberpunk", "Cyberpunk"), P("Fantasy", "Fantastik"), P("Retro", "Retro"), P("Vintage", "Vintage"), P("Minimalist", "Minimalist"), P("Noir", "Noir"), P("Steampunk", "Steampunk"), P("Dark Fantasy", "Dark Fantasy"), P("Low Poly", "Low Poly"), P("Futuristic", "Futuristik"), P("Editorial", "Editorial"), P("Luxury", "Luxury"), P("Streetwear", "Streetwear"), P("Dark", "Dark"), P("Surreal", "Surreal")], "sparkles", P("Visual looks and aesthetic directions.", "Görsel üslup ve estetik yönler.")],
    [P("Product & Commercial", "Ürün & Ticari"), [P("Product", "Ürün Görseli"), P("Advertising", "Reklam"), P("E-commerce", "E-ticaret"), P("Packaging", "Ambalaj"), P("Brand", "Marka"), P("Logo", "Logo"), P("Product Mockup", "Ürün Mockup"), P("Cosmetics", "Kozmetik"), P("Clothing", "Giyim"), P("Technology", "Teknoloji"), P("Fashion Product", "Moda Ürünü"), P("Food & Beverage", "Yiyecek & İçecek")], "shopping-bag", P("Product, advertising and brand visuals.", "Ürün, reklam ve marka görselleri.")],
    [P("Spaces", "Mekân"), [P("Architecture", "Mimari"), P("Interior", "İç Mekân"), P("Exterior", "Dış Mekân"), P("Home", "Ev"), P("Office", "Ofis"), P("Restaurant", "Restoran"), P("Store", "Mağaza"), P("City", "Şehir"), P("Village", "Köy"), P("Futuristic City", "Fütüristik Şehir"), P("Hotel", "Otel"), P("Room Design", "Oda Tasarımı")], "building-2", P("Interiors, exteriors and architectural scenes.", "İç ve dış mekânlar, mimari sahneler.")],
    [P("Nature & Environment", "Doğa & Çevre"), [P("Landscape", "Manzara"), P("Mountain", "Dağ"), P("Sea", "Deniz"), P("Forest", "Orman"), P("Desert", "Çöl"), P("Animal", "Hayvan"), P("Plant", "Bitki"), P("Space", "Uzay"), P("Planet", "Gezegen"), P("Weather", "Hava Durumu"), P("Flower", "Çiçek"), P("Sunset", "Gün Batımı"), P("Sky", "Gökyüzü"), P("Seasons", "Mevsimler")], "leaf", P("Nature, animals, sky and environment.", "Doğa, hayvanlar, gökyüzü ve çevre.")],
    [P("Design", "Tasarım"), [P("UI", "UI"), P("UX", "UX"), P("Web Design", "Web Tasarımı"), P("Mobile App", "Mobil Tasarım"), P("Dashboard", "Dashboard"), P("Poster", "Poster"), P("Banner", "Afiş / Banner"), P("Social Media", "Sosyal Medya"), P("Presentation", "Sunum"), P("Infographic", "Infografik"), P("Logo Design", "Logo"), P("Branding", "Branding"), P("Typography", "Tipografi"), P("3D Design", "3D Tasarım"), P("Graphic Design", "Grafik Tasarım")], "pen-tool", P("Interfaces, posters, logos and graphic design.", "Arayüz, poster, logo ve grafik tasarım.")],
  ],
  text: [
    [P("Writing", "Yazarlık"), [P("Story", "Hikâye"), P("Novel", "Roman"), P("Screenplay", "Senaryo"), P("Poetry", "Şiir"), P("Dialogue", "Diyalog"), P("Character Writing", "Karakter Yazımı"), P("World Building", "Dünya Kurma"), P("Fiction", "Kurgu"), P("Creative Writing", "Yaratıcı Yazarlık")], "pen-line", P("Stories, poetry and creative writing.", "Hikâye, şiir ve yaratıcı yazarlık.")],
    [P("Social Media", "Sosyal Medya"), [P("Instagram", "Instagram"), P("TikTok", "TikTok"), P("YouTube", "YouTube"), P("X / Twitter", "X / Twitter"), P("LinkedIn", "LinkedIn"), P("Facebook", "Facebook"), P("Social Media Caption", "Sosyal Medya Açıklaması"), P("Social Media Post", "Sosyal Medya Gönderisi"), P("Viral Content", "Viral İçerik")], "share-2", P("Social media posts and captions.", "Sosyal medya gönderileri ve açıklamaları.")],
    [P("Marketing", "Pazarlama"), [P("Ad Copy", "Reklam Metni"), P("Sales Copy", "Satış Metni"), P("Product Description", "Ürün Açıklaması"), P("Landing Page", "Landing Page"), P("Email Marketing", "E-posta Pazarlama"), P("Campaign", "Kampanya"), P("Brand Copy", "Marka Metni"), P("Slogan", "Slogan"), P("CTA", "CTA")], "megaphone", P("Ad, sales and campaign copy.", "Reklam, satış ve kampanya metinleri.")],
    [P("SEO", "SEO"), [P("SEO Article", "SEO Makalesi"), P("Blog", "Blog"), P("Keyword", "Anahtar Kelime"), P("Meta Description", "Meta Description"), P("Headline", "Başlık"), P("Product SEO", "Ürün SEO"), P("Content Optimization", "İçerik Optimizasyonu")], "search", P("SEO articles, keywords and headlines.", "SEO makaleleri, anahtar kelime ve başlıklar.")],
    [P("Business & Professional", "İş & Profesyonel"), [P("Email", "E-posta"), P("Resume", "CV"), P("Cover Letter", "Ön Yazı"), P("Report", "Rapor"), P("Presentation", "Sunum"), P("Meeting Summary", "Toplantı Özeti"), P("Business Plan", "İş Planı"), P("Proposal", "Teklif"), P("Documentation", "Dokümantasyon")], "briefcase", P("Emails, reports, résumés and business documents.", "E-posta, rapor, CV ve iş belgeleri.")],
    [P("Education", "Eğitim"), [P("Lesson", "Ders"), P("Homework", "Ödev"), P("Exam", "Sınav"), P("Quiz", "Quiz"), P("Lesson Plan", "Ders Planı"), P("Summary", "Özet"), P("Flashcard", "Flashcard"), P("Teacher", "Öğretmen"), P("Student", "Öğrenci")], "graduation-cap", P("Lessons, homework, exams and teaching material.", "Ders, ödev, sınav ve öğretim içerikleri.")],
    [P("Research", "Araştırma"), [P("Research", "Araştırma"), P("Summarization", "Özetleme"), P("Analysis", "Analiz"), P("Comparison", "Karşılaştırma"), P("Data Analysis", "Veri Analizi"), P("Literature", "Literatür"), P("Reporting", "Raporlama")], "microscope", P("Research, summaries and analysis.", "Araştırma, özet ve analiz.")],
    [P("Coding", "Kodlama"), [P("Code", "Kod"), P("Web", "Web"), P("Mobile", "Mobil"), P("Frontend", "Frontend"), P("Backend", "Backend"), P("JavaScript", "JavaScript"), P("TypeScript", "TypeScript"), P("Python", "Python"), P("SQL", "SQL"), P("API", "API"), P("Debugging", "Debugging"), P("Automation", "Otomasyon")], "code", P("Writing code, debugging and automation.", "Kod yazma, hata ayıklama ve otomasyon.")],
  ],
  audio: [
    [P("Music", "Müzik"), [P("Song", "Şarkı"), P("Instrumental", "Enstrümantal"), P("Beat", "Beat"), P("Electronic", "Elektronik"), P("Rock", "Rock"), P("Pop", "Pop"), P("Hip Hop", "Hip Hop"), P("Rap", "Rap"), P("Jazz", "Jazz"), P("Classical", "Klasik"), P("Ambient", "Ambient"), P("Lo-fi", "Lo-fi"), P("Synthwave", "Synthwave"), P("Metal", "Metal"), P("Folk", "Folk"), P("Film Score", "Film Müziği"), P("Game Music", "Oyun Müziği")], "music", P("Songs, genres and instrumentals.", "Şarkılar, tür ve enstrümantal çalışmalar.")],
    [P("Vocals", "Vokal"), [P("Female Vocal", "Kadın Vokal"), P("Male Vocal", "Erkek Vokal"), P("Choir", "Koro"), P("Backing Vocal", "Arka Vokal"), P("Rap Vocal", "Rap Vokal"), P("Spoken Word", "Spoken Word")], "mic", P("Vocal types and singing styles.", "Vokal türleri ve söyleyiş tarzları.")],
    [P("Voiceover", "Seslendirme"), [P("Advertisement", "Reklam"), P("Dubbing", "Dublaj"), P("Story", "Hikâye"), P("Podcast", "Podcast"), P("Education", "Eğitim"), P("Narrator", "Anlatıcı"), P("Character Voice", "Karakter Sesi")], "mic-vocal", P("Voiceover, dubbing and narration.", "Seslendirme, dublaj ve anlatıcı sesleri.")],
    [P("Sound Effects", "Ses Efektleri"), [P("SFX", "SFX"), P("Cinematic Effect", "Sinematik Efekt"), P("Game Effect", "Oyun Efekti"), P("Nature Sounds", "Doğa Sesleri"), P("Ambience", "Ortam"), P("Foley", "Foley"), P("UI Sounds", "UI Sesleri"), P("Transition Sounds", "Geçiş Sesleri")], "audio-lines", P("Sound effects and foley.", "Ses efektleri ve foley.")],
    [P("Podcast", "Podcast"), [P("Podcast Intro", "Podcast Giriş"), P("Podcast Outro", "Podcast Çıkış"), P("Podcast Conversation", "Podcast Konuşması"), P("Interview", "Röportaj"), P("Storytelling", "Hikâye Anlatımı")], "podcast", P("Podcast intros, conversations and interviews.", "Podcast girişleri, konuşmaları ve röportajlar.")],
    [P("Ambience", "Ortam"), [P("Rain", "Yağmur"), P("Forest", "Orman"), P("City", "Şehir"), P("Cafe", "Kafe"), P("Sea", "Deniz"), P("Storm", "Fırtına"), P("Space", "Uzay"), P("Horror", "Korku"), P("Ambient", "Ambient")], "waves", P("Ambient sounds and atmospheres.", "Ortam sesleri ve atmosferler.")],
  ],
  video: [
    [P("Cinematic", "Sinematik"), [P("Film", "Film"), P("Cinematic Scene", "Sinematik Sahne"), P("Trailer", "Trailer"), P("Teaser", "Teaser"), P("Film Intro", "Film Intro"), P("Film Outro", "Film Outro")], "clapperboard", P("Film, trailers and cinematic scenes.", "Film, fragman ve sinematik sahneler.")],
    [P("Social Media", "Sosyal Medya"), [P("TikTok", "TikTok"), P("Reels", "Reels"), P("Shorts", "Shorts"), P("YouTube", "YouTube"), P("Story", "Story"), P("Viral Video", "Viral Video")], "smartphone", P("Short-form video and social formats.", "Kısa video ve sosyal medya formatları.")],
    [P("Advertising", "Reklam"), [P("Product Ad", "Ürün Reklamı"), P("Brand Ad", "Marka Reklamı"), P("Social Media Ad", "Sosyal Medya Reklamı"), P("UGC", "UGC"), P("Product Presentation", "Ürün Tanıtımı"), P("Campaign", "Kampanya")], "megaphone", P("Product and brand advertising videos.", "Ürün ve marka reklam videoları.")],
    [P("Animation", "Animasyon"), [P("2D", "2D"), P("3D", "3D"), P("Anime", "Anime"), P("Motion Graphics", "Motion Graphics"), P("Character Animation", "Character Animation"), P("Explainer", "Explainer"), P("Cartoon", "Cartoon")], "shapes", P("2D, 3D and motion-graphics animation.", "2D, 3D ve hareketli grafik animasyonlar.")],
    [P("Music Video", "Müzik Videosu"), [P("Music Video", "Klip"), P("Lyric Video", "Lyric Video"), P("Visualizer", "Visualizer"), P("Concert", "Konser"), P("Performance", "Performans")], "disc-3", P("Music videos, lyric videos and visualizers.", "Klip, lyric video ve görselleştirmeler.")],
    [P("Education", "Eğitim"), [P("Tutorial", "Tutorial"), P("Lesson", "Ders"), P("Explainer", "Explainer"), P("Presentation", "Sunum"), P("Screen Recording", "Ekran Kaydı"), P("Educational Animation", "Eğitim Animasyonu")], "graduation-cap", P("Tutorials and educational video.", "Eğitim videoları ve anlatımlar.")],
    [P("Story & Entertainment", "Hikâye & Eğlence"), [P("Short Film", "Kısa Film"), P("Story", "Hikâye"), P("Comedy", "Komedi"), P("Horror", "Korku"), P("Action", "Aksiyon"), P("Drama", "Dram"), P("Fantasy", "Fantastik"), P("Sci-Fi", "Bilim Kurgu")], "popcorn", P("Short films, comedy, drama and action.", "Kısa film, komedi, dram ve macera.")],
    [P("Visual Effects", "Görsel Efekt"), [P("VFX", "VFX"), P("CGI", "CGI"), P("Green Screen", "Green Screen"), P("Transition", "Transition"), P("Slow Motion", "Slow Motion"), P("Time Lapse", "Time Lapse"), P("Camera Effects", "Camera Effects")], "wand-sparkles", P("VFX, transitions and camera effects.", "VFX, geçişler ve kamera efektleri.")],
    [P("Product & Commercial", "Ürün & Ticari"), [P("Product Video", "Ürün Videosu"), P("E-commerce", "E-ticaret"), P("Product Presentation", "Ürün Tanıtımı"), P("Fashion", "Moda"), P("Automotive", "Otomobil"), P("Technology", "Teknoloji"), P("Restaurant", "Restoran")], "package", P("Product showcases and commercial video.", "Ürün tanıtımı ve ticari videolar.")],
    [P("Documentary", "Belgesel"), [P("Nature", "Doğa"), P("History", "Tarih"), P("Science", "Bilim"), P("Travel", "Seyahat"), P("Interview", "Röportaj"), P("News", "Haber")], "video", P("Documentary and news-style content.", "Belgesel ve haber tarzı içerikler.")],
  ],
};

export const TYPE_LABELS: Record<ContentTypeId, Pair> = {
  image: ["Image", "Görsel"],
  text: ["Text", "Metin"],
  audio: ["Audio", "Ses"],
  video: ["Video", "Video"],
};
