import {
  AudioLines,
  Briefcase,
  Building2,
  Camera,
  Clapperboard,
  Code,
  Disc3,
  Folder,
  GraduationCap,
  Leaf,
  Megaphone,
  Mic,
  MicVocal,
  Microscope,
  Music,
  Package,
  PenLine,
  PenTool,
  Podcast,
  Palette,
  Popcorn,
  Search,
  Shapes,
  Share2,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Users,
  Video,
  WandSparkles,
  Waves,
  type LucideIcon,
} from "lucide-react";

/**
 * Category icon names stored in `taxonomy_categories.icon` (kebab-case Lucide
 * names) -> the component. A name this map doesn't know falls back to a
 * folder, so a new database row never crashes the picker.
 */
export const TAXONOMY_ICONS: Record<string, LucideIcon> = {
  users: Users,
  camera: Camera,
  palette: Palette,
  sparkles: Sparkles,
  "shopping-bag": ShoppingBag,
  "building-2": Building2,
  leaf: Leaf,
  "pen-tool": PenTool,
  "pen-line": PenLine,
  "share-2": Share2,
  megaphone: Megaphone,
  search: Search,
  briefcase: Briefcase,
  "graduation-cap": GraduationCap,
  microscope: Microscope,
  code: Code,
  music: Music,
  mic: Mic,
  "mic-vocal": MicVocal,
  "audio-lines": AudioLines,
  podcast: Podcast,
  waves: Waves,
  clapperboard: Clapperboard,
  smartphone: Smartphone,
  shapes: Shapes,
  "disc-3": Disc3,
  popcorn: Popcorn,
  "wand-sparkles": WandSparkles,
  package: Package,
  video: Video,
};

/** Shown for an icon name `TAXONOMY_ICONS` doesn't have. */
export const FALLBACK_TAXONOMY_ICON: LucideIcon = Folder;
